server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: eden
    password: paroxx645213

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
